---
- name: USE | Detect upstart system
  become: true
  shell: |
    if [[ `/sbin/init --version 2> /dev/null` =~ upstart ]]; then echo upstart;
    elif [[ `systemctl` =~ -\.mount ]]; then echo systemd;
    elif [[ -f /etc/init.d/cron && ! -h /etc/init.d/cron ]]; then echo sysv-init;
    else echo UNKNOWN;
    fi
  args:
    executable: /bin/bash
  changed_when: false
  register: upstart_detect_raw

- name: Set fact for upstart_system
  set_fact:
    upstart_system: "{{ upstart_detect_raw.stdout }}"
